apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: fullstackapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 396953591548.dkr.ecr.eu-west-1.amazonaws.com/fullstackapp
        ports:
        - containerPort: 80
