<?php

namespace AppBundle\Repository;

/**
 * LegoPiecesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LegoPiecesRepository extends \Doctrine\ORM\EntityRepository
{
}
